'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Footer from '@/components/Footer'

export default function HistoryPage() {
  const router = useRouter()
  const [user, setUser] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [allLaundry, setAllLaundry] = useState<any[]>([])
  const [totalSpent, setTotalSpent] = useState(0)

  useEffect(() => {
    const savedUser = localStorage.getItem('user')
    if (savedUser) {
      const userData = JSON.parse(savedUser)
      setUser(userData)
      
      const laundryKey = `laundry_${userData.id}`
      const savedLaundry = localStorage.getItem(laundryKey)
      if (savedLaundry) {
        const laundry = JSON.parse(savedLaundry)
        setAllLaundry(laundry)
        
        const total = laundry.reduce((sum: number, item: any) => {
          return sum + (item.amount || 0)
        }, 0)
        setTotalSpent(total)
      }
    }
    setLoading(false)
  }, [])

  const handleBack = () => {
    router.push('/dashboard')
  }

  const downloadPDF = () => {
    const today = new Date().toLocaleDateString()
    
    let tableRows = ''
    allLaundry.forEach((item: any) => {
      tableRows += `
        <tr>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.date}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.pairs}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.singles || 0}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.serviceType || 'Clothes'}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.pickupStatus === 'Picked Up' ? 'Yes' : 'No'}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${item.pickupDate || '-'}</td>
          <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">₹${item.amount}</td>
        </tr>
      `
    })

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Laundry History - ${user?.name}</title>
        <style>
          body { font-family: 'Poppins', Arial, sans-serif; margin: 40px; background: #f5f3ff; }
          .header { text-align: center; margin-bottom: 30px; }
          .logo { font-size: 48px; }
          h1 { color: #4f46e5; font-weight: 600; }
          h3 { color: #4f46e5; font-weight: 500; }
          .info { margin-bottom: 20px; background: #f3e8ff; padding: 15px; border-radius: 10px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background-color: #4f46e5; color: white; padding: 10px; border: 1px solid #ddd; font-weight: 500; }
          td { padding: 8px; border: 1px solid #ddd; }
          .total { margin-top: 20px; text-align: right; font-size: 18px; font-weight: 600; color: #ea580c; }
          .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">🧺</div>
          <h1>WashMate</h1>
          <h3>Customer History Report</h3>
        </div>
        
        <div class="info">
          <p><strong>Customer Name:</strong> ${user?.name}</p>
          <p><strong>Email:</strong> ${user?.email}</p>
          <p><strong>Generated On:</strong> ${today}</p>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Pairs</th>
              <th>Single</th>
              <th>Service</th>
              <th>Picked Up</th>
              <th>Pickup Date</th>
              <th>Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        
        <div class="total">
          Total Amount Spent: ₹${totalSpent}
        </div>
        
        <div class="footer">
          <p>Thank you for choosing WashMate!</p>
          <p>Generated by WashMate Laundry Management System</p>
        </div>
      </body>
      </html>
    `

    const blob = new Blob([htmlContent], { type: 'text/html' })
    const link = document.createElement('a')
    const url = URL.createObjectURL(blob)
    link.href = url
    link.download = `laundry_history_${user?.name}_${today}.html`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    alert('History report downloaded! Open the HTML file in browser to view.')
  }

  if (loading) {
    return (
      <div 
        className="min-h-screen flex items-center justify-center"
        style={{ background: 'linear-gradient(to bottom right, #e0e7ff, #ffffff, #f3e8ff)' }}
      >
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-gray-500">Loading history...</p>
        </div>
      </div>
    )
  }

  if (!user) {
    router.push('/login')
    return null
  }

  return (
    <div 
      className="min-h-screen flex flex-col"
      style={{ background: 'linear-gradient(to bottom right, #e0e7ff, #ffffff, #f3e8ff)' }}
    >
      {/* Navbar */}
      <nav className="bg-white/80 backdrop-blur-sm shadow-sm border-b border-indigo-100 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-3">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-semibold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
              🧺 WashMate
            </h1>
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-600 bg-indigo-50 px-3 py-1 rounded-full">👋 {user.name}</span>
              <button 
                onClick={handleBack}
                className="text-indigo-500 hover:text-indigo-600 font-medium"
              >
                ← Back to Dashboard
              </button>
            </div>
          </div>
        </div>
      </nav>

      <div className="flex-1 max-w-7xl mx-auto px-4 py-6">
        {/* Header */}
        <div className="mb-6 flex justify-between items-center flex-wrap gap-4">
          <div>
            <h2 className="text-2xl font-semibold text-gray-700">
              📜 Complete Laundry History
            </h2>
            <p className="text-gray-400">All your laundry records from first day to today</p>
          </div>
          {allLaundry.length > 0 && (
            <button
              onClick={downloadPDF}
              className="bg-green-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-green-700 transition-all flex items-center gap-2"
            >
              📥 Download as PDF
            </button>
          )}
        </div>

        {/* Customer Info Card */}
        <div className="bg-white rounded-xl shadow-lg p-6 border border-indigo-100 mb-6">
          <h3 className="text-lg font-medium text-gray-700 mb-3">👤 Customer Information</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-400">Full Name</p>
              <p className="font-medium text-gray-700">{user.name}</p>
            </div>
            <div>
              <p className="text-sm text-gray-400">Email Address</p>
              <p className="font-medium text-gray-700">{user.email}</p>
            </div>
          </div>
        </div>

        {/* History Table */}
        <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-indigo-100">
          <div className="px-6 py-4 border-b bg-gradient-to-r from-indigo-50 to-purple-50">
            <h3 className="text-lg font-medium text-gray-700">📋 All Laundry Records</h3>
          </div>
          
          {allLaundry.length === 0 ? (
            <div className="px-6 py-12 text-center text-gray-400">
              🧺 No laundry records found. Start your first order!
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-indigo-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Date</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Pairs</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Single</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Service</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Status</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Pickup Date</th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-indigo-600">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {allLaundry.map((item: any, index: number) => (
                    <tr key={item.id} className={`border-t border-indigo-50 hover:bg-indigo-50/30 transition-colors ${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'}`}>
                      <td className="px-4 py-3 text-sm text-gray-600">{item.date}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">{item.pairs}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">{item.singles || 0}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">{item.serviceType || 'Clothes'}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                          item.pickupStatus === 'Picked Up' 
                            ? 'bg-green-100 text-green-600' 
                            : item.status === 'Ready' 
                              ? 'bg-blue-100 text-blue-600' 
                              : 'bg-amber-100 text-amber-600'
                        }`}>
                          {item.pickupStatus === 'Picked Up' 
                            ? '✅ Completed' 
                            : item.status === 'Ready' 
                              ? 'Ready' 
                              : 'Received'}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-600">{item.pickupDate || '-'}</td>
                      <td className="px-4 py-3 text-sm font-medium text-gray-700">₹{item.amount}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot className="bg-indigo-50 border-t border-indigo-100">
                  <tr>
                    <td colSpan={6} className="px-4 py-3 text-right font-medium text-gray-600">
                      Total Spent:
                    </td>
                    <td className="px-4 py-3 text-lg font-bold text-orange-600">
                      ₹{totalSpent}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          )}
        </div>

        {/* Back Button */}
        <div className="mt-6 flex justify-center">
          <button
            onClick={handleBack}
            className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-indigo-700 transition-all"
          >
            ← Back to Dashboard
          </button>
        </div>
      </div>
      <Footer />
    </div>
  )
}